# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
dimension = A.ndim
shape = A.shape
size = A.size
datatype = A.dtype

print(f"Dimension: {dimension}")
print()
print(f"Shape: {shape}")
print()
print(f"Size: {size}")
print()
print(f"Datatype: {datatype}")

Dimension: 2

Shape: (3, 5)

Size: 15

Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [7]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [13]:
print("Elementwise subtraction")
print(B - C)
print()
print("Elementwise multiplication")
print(B * C)
print()
print("Matrix multiplication")
print(B @ C)

Elementwise subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print("Exponentiate each number elementwise")
print(np.exp(D))
print()

print("Minmnum value in the whole matrix")
print(D.min())
print()

print("Minimum value in each row")
print(D.min(axis=1))
print()

print("Minumum value in each column")
print(D.min(axis=0))
print()

print("Find index value for the minimum value in the whole matrix")
print(np.argmin(D))
print()

print("Find index value for the minimum value in eacg row")
print(np.argmin(D, axis=1))
print()

print("Calculate the sum for all elements")
print(D.sum())
print()

print("Calculate the mean value for each column")
print(D.mean(axis=0))
print()

print("Calculate the median value for each column")
print(np.median(D, axis=0))


Exponentiate each number elementwise
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minmnum value in the whole matrix
1

Minimum value in each row
[1 4 7]

Minumum value in each column
[1 2 3]

Find index value for the minimum value in the whole matrix
0

Find index value for the minimum value in eacg row
[0 0 0]

Calculate the sum for all elements
45

Calculate the mean value for each column
[4. 5. 6.]

Calculate the median value for each column
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# When fewer indices are provided than number of axes, the missing indices are considered complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [13]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
for i in A:
    for j in i:
        print(j)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [3]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


The code creates an array with one dimension (1d) and stores it in variable 'a' after that it reshapes the array to an array with three dimensions (3d) and stores it in variable 'b'. Then it prints out both arrays.


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [3]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [4]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [5]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [8]:
import numpy as np

def add_mult_matrices(matrix_1, matrix_2, mathematical_operation):
    
    if isinstance(matrix_1, np.ndarray) and isinstance(matrix_2, np.ndarray):
        if mathematical_operation.lower() == "add":
            if matrix_1.shape == matrix_2.shape:
                return matrix_1 + matrix_2
            else:
                return "The matrices has different sizes so can not perform addition."
        elif mathematical_operation.lower() == "multiply":
            if matrix_1.shape[1] == matrix_2.shape[0]:
                return matrix_1 @ matrix_2
            else:
                return "Number of columns in first matrix must be equal to number of rows in the second matrax."
        else:
            return "Choose either \"add\" or \"multiply\""
    else:
        return "Please check your inputs! They should be of format numpy.ndarray."
    


In [10]:
# Set up arrays for testing the function 'add_mult_matrices'
m_1 = np.array([[2, 5], [3, 5]])
m_2 = np.array([[2, 5], [1, 4]])
m_3 = np.array([[1, 2, 3], [4, 5, 6]])
m_4 = np.array([[7, 8], [9, 10], [11, 12]])

# Test the function 'add_mult_matrices'
add = add_mult_matrices(m_1, m_2, "add")
add_with_wrong_sized_matrices = add_mult_matrices(m_1, m_3, "add")
multiply = add_mult_matrices(m_3, m_4, "multiply")
multiply_with_wrong_shaped_matrices = add_mult_matrices(m_3, m_2, "multiply")
error = add_mult_matrices(m_1, m_2, "Wrong")
wrong_array_type = add_mult_matrices([2, 5], [1, 4], "add")

# Print the results
print("Addition")
print(add)
print()

print("Wrong sized matrices")
print(add_with_wrong_sized_matrices)
print()

print("Multiplication")
print(multiply)
print()

print("Wrong shaped matrices")
print(multiply_with_wrong_shaped_matrices)
print()

print("Error")
print(error)
print()

print("Wrong array type")
print(wrong_array_type)


Addition
[[ 4 10]
 [ 4  9]]

Wrong sized matrices
The matrices has different sizes so can not perform addition.

Multiplication
[[ 58  64]
 [139 154]]

Wrong shaped matrices
Number of columns in first matrix must be equal to number of rows in the second matrax.

Error
Choose either "add" or "multiply"

Wrong array type
Please check your inputs! They should be of format numpy.ndarray.


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [116]:
# 10.1.1

x = np.array([4, 3])
m_a = x.ndim
m_b = x * 5
m_c = x * 3
m_d = add_mult_matrices(m_b, m_c, "add")
m_e = x * 8
m_f = ((x *4) - (x))
m_g = np.transpose(x).ndim
m_h = x == m_g
m_i = np.linalg.norm(x)

# Print all results
print(f"a {m_a} - (1 x 2)") 
print(f"b: {m_b}")
print(f"c {m_c}")
print(f"d: {m_d}")
print(f"e: {m_e}")
print(f"f: {m_f}")
print(f"g: {m_g}")
print(f"h: {m_h}")
print(f"i: {m_i}")


a 1 - (1 x 2)
b: [20 15]
c [12  9]
d: [32 24]
e: [32 24]
f: [12  9]
g: 1
h: [False False]
i: 5.0


In [117]:
# 10.1.2

v = np.array([3, 7, 0, 11]).reshape(4, 1)

print(f"a: {v.ndim} - (4 x 1)")
print(f"b: {2 * v}")
print(f"c: {add_mult_matrices((5 * v), (2 * v), "add") }")
print(f"d: {(4 * v) - (2 *v)}")
print(f"e: {np.transpose(v).shape}")
print(f"f: {np.linalg.norm(v)}")


a: 2 - (4 x 1)
b: [[ 6]
 [14]
 [ 0]
 [22]]
c: [[21]
 [49]
 [ 0]
 [77]]
d: [[ 6]
 [14]
 [ 0]
 [22]]
e: (1, 4)
f: 13.379088160259652


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
# 10.2.1

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

not_defined_str = "Not defined!"

print(2 * A)
print((B - (2 * A)) if B.shape == (2 * A).shape else not_defined_str)
print((3 * C) - (2 * E) if (3 * C).shape == (2 * E).shape else not_defined_str)
print((2 * D) - (3 * C) if (2 * D).shape == (3 * C).shape else not_defined_str)
print(np.transpose(D) + (2 * D) if (np.transpose(D)).shape == (2 * D).shape else not_defined_str)
print(np.transpose((2 * C)) - np.transpose((2 * D)) if np.transpose((2 * C)).shape == np.transpose((2 * D)).shape else not_defined_str)
print(np.transpose(A) - B if (np.transpose(A)).shape == B.shape else not_defined_str)
print(A @ C if A.shape[1] == C.shape[0] else not_defined_str)
print(C @ D if C.shape[1] == D.shape[0] else not_defined_str)
print(C @ B if C.shape[1] == B.shape[0] else not_defined_str)
print(C @ I if C.shape[1] == I.shape[0] else not_defined_str)
print(A @ np.transpose(B) if A.shape[1] == np.transpose(B).shape[0] else not_defined_str)


[[ 4  2 -2]
 [ 2 -2  2]]
[[ 0 -4  3]
 [ 0 -2 -4]]
Not defined!
[[3 2]
 [2 3]]
[[ 9 12]
 [12  9]]
[[-4 -4]
 [-4 -4]]
Not defined!
Not defined!
[[11 10]
 [10 11]]
[[  8 -10  -3]
 [ 10  -8   0]]
[[1 2]
 [2 1]]
[[5 2]
 [7 4]]

[[6 0]
 [0 3]]


In [ ]:
# 10.2.2

A = np.array([[2, 3, 4], [5, 4, 1]])

print(A @ np.transpose(A) if A.shape[1] == np.transpose(A).shape[0] else not_defined_str)

[[29 26]
 [26 42]]


In [ ]:
# 10.2.3

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print((A @ B))
print((A @ C))
print(f"Is AB equal to AC: {np.array_equiv((A @ B), (A @ C))}")

print(f"Is B equal to C: {np.array_equiv(B, C)}")

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
Is AB equal to AC: True
Is B equal to C: False


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

print(v1.base)
print(v2.base)
print("v1 is a copy" if v1.base is None else "v1 is a view")
print("v2 is a copy" if v2.base is None else "v2 is a view")
print(v2.base)

v2[1] = 123
print(v1)
print(v2)

# If we change values in v2, that is athe view, it also reflect on v1 that is the original copy.

[0 1 2 3]
[2 3]
None
[0 1 2 3]
v1 is a copy
v2 is a view
[0 1 2 3]
[  0   1   2 123]
[  2 123]
